services:
  db_postgres_test:
    image: postgres
    container_name: db_postgres_test
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  node_app_test:
    container_name: node_app_test
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_test
    env_file:
      - .env.test